steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/gurukul-lms-ms/gurukul-repo/gurukul-sm-api', '.']
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/gurukul-lms-ms/gurukul-repo/gurukul-sm-api']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gurukul-sm-api'
    - '--image'
    - 'asia-south1-docker.pkg.dev/gurukul-lms-ms/gurukul-repo/gurukul-sm-api'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--project'
    - 'gurukul-lms-ms'
images:
  - 'asia-south1-docker.pkg.dev/gurukul-lms-ms/gurukul-repo/gurukul-sm-api' 