steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gurukul-lms-ms/studentmate-repo/studentmate-api', '.']
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gurukul-lms-ms/studentmate-repo/studentmate-api']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'studentmate-api'
    - '--image'
    - 'us-central1-docker.pkg.dev/gurukul-lms-ms/studentmate-repo/studentmate-api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--project'
    - 'gurukul-lms-ms'
images:
  - 'us-central1-docker.pkg.dev/gurukul-lms-ms/studentmate-repo/studentmate-api' 